/**
 * Visual-editor schemas derived from the generated policy catalogue.
 *
 * `POLICY_SCHEMAS` (policySchema.ts) is hand-written and hand-checked, and it
 * covers the dozen-odd policy types this workspace leans on hardest. The other
 * forty-odd had no visual editor at all — not because they are hard, but
 * because writing forty schemas by hand is forty chances to mistype an element
 * name, and a mistyped element name in a visual editor is a policy that
 * silently does nothing.
 *
 * So they are derived instead, from the same catalogue the XML editor already
 * trusts for completion: scraped from the Apigee X reference, regenerated by
 * `npm run generate:policy-schemas`, and guarded by `npm run
 * test:policy-schemas`. Every element name, enumeration and required marker in
 * a derived schema traces back to a documented row rather than to typing.
 *
 * Hand-written always wins — `getPolicySchema` only reaches here when
 * POLICY_SCHEMAS has nothing to say about a type. Deriving is for breadth;
 * authoring is for the policies that deserve an opinion about how their fields
 * should be grouped and what goes wrong with them.
 *
 * What derivation deliberately will not do:
 *
 *   - **Guess at defaults.** A `default:` in a schema is what the editor shows
 *     for an absent element, and showing Apigee's documented default as though
 *     the policy had set it is how you end up writing it back. Documented
 *     defaults become placeholder text, which informs without asserting.
 *   - **Flatten a repeating structure.** ExtractVariables' <Variable> and
 *     DataCapture's <Capture> repeat with children of their own, which none of
 *     the field types can express. The section says so and points at the XML
 *     tab rather than rendering a field that would edit only the first one.
 */

import { GENERATED_POLICY_ELEMENTS } from './generated/apigeePolicyElements';
import type { XmlElementDef } from './policyXmlSchema';
import type { PFElementAttr, PolicyField, PolicyFieldSection, PolicySchema, RootAttrDef } from './policySchema';

/** Rendered by the editor itself, not as a field. */
const EDITOR_OWNED = new Set(['DisplayName']);

/** How deep a field's path may run before the XML tab is the better tool. */
const MAX_PATH_DEPTH = 4;

const BOOLEAN_VALUES = new Set(['true', 'false']);

/** Element names whose value is a count, a duration or a size. */
const NUMERIC_NAME = /(Seconds|Secs|Count|Size|Port|Interval|Timeout|Limit|Depth|Length|MaxAge|Age|Weight|Lifespan|Expires|Bytes|Entries|Attempts)$/;

function isBoolean(def: XmlElementDef): boolean {
  const values = def.values || [];
  return values.length > 0 && values.every((v) => BOOLEAN_VALUES.has(v.toLowerCase()));
}

/** A label a person can read, from a tag written in PascalCase. */
export function labelFor(tag: string): string {
  return (tag.charAt(0).toUpperCase() + tag.slice(1))
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1 $2')
    .replace(/\bApi\b/g, 'API')
    .replace(/\bUrl\b/g, 'URL')
    .replace(/\bUri\b/g, 'URI')
    .replace(/\bJwt\b/g, 'JWT')
    .replace(/\bJws\b/g, 'JWS')
    .replace(/\bXml\b/g, 'XML')
    .replace(/\bJson\b/g, 'JSON')
    .replace(/\bKvm\b/g, 'KVM');
}

/** Stable, unique per schema: the element path is already unique. */
const idFor = (path: string[]) => path.map((p, i) => (i ? p : p.charAt(0).toLowerCase() + p.slice(1))).join('.');

function attrDefs(def: XmlElementDef): PFElementAttr[] {
  return (def.attrs || []).map((a) => ({
    name: a.name,
    label: labelFor(a.name),
    kind: a.values && a.values.length > 1 ? ('select' as const) : ('text' as const),
    ...(a.values && a.values.length > 1 ? { options: a.values } : {}),
  }));
}

/**
 * One element with no children of its own.
 *
 * `ref` is singled out because an element whose only attribute is `ref` is the
 * reference's way of writing "a literal or a flow variable", which is exactly
 * what the `ref` field type offers as a toggle.
 */
function leafField(def: XmlElementDef, path: string[]): PolicyField {
  const common = {
    id: idFor(path),
    label: labelFor(def.name),
    ...(def.doc ? { help: def.doc } : {}),
    ...(def.required ? { required: true } : {}),
  };
  const attrs = def.attrs || [];
  const onlyRef = attrs.length === 1 && attrs[0].name === 'ref';

  if (isBoolean(def)) {
    return { ...common, type: 'boolean', path, default: def.default === 'true' ? 'true' : 'false', omitIfDefault: true };
  }
  if (def.values && def.values.length > 1) {
    // A leading blank keeps "not set" expressible; a required element has no
    // such state, so it doesn't get one.
    return { ...common, type: 'select', path, options: def.required ? def.values : ['', ...def.values] };
  }
  if (onlyRef || def.takesVariable) {
    return { ...common, type: 'ref', path };
  }
  if (attrs.length) {
    return { ...common, type: 'element', path, attrs: attrDefs(def), hasText: true, textLabel: 'Value' };
  }
  const numeric = NUMERIC_NAME.test(def.name) || (def.default !== undefined && /^-?\d+$/.test(def.default));
  return {
    ...common,
    type: numeric ? 'number' : 'text',
    path,
    ...(def.default !== undefined ? { placeholder: def.default } : {}),
  };
}

/** The single repeating child that makes `def` a list, if it has one. */
function listChild(def: XmlElementDef): XmlElementDef | null {
  const children = def.children || [];
  if (children.length !== 1) return null;
  const child = children[0];
  if (!child.repeatable || (child.children || []).length) return null;
  return child;
}

interface Derived {
  fields: PolicyField[];
  /** Structures no field type can express, named so the section can say so. */
  skipped: string[];
}

function fieldsFor(def: XmlElementDef, path: string[], out: Derived) {
  const children = def.children || [];

  // A leaf is one field even when it carries attributes: <Pattern
  // ignoreCase="true">regex</Pattern> is an attribute *and* a value, and
  // emitting only the attribute would leave the regex with nowhere to go.
  if (!children.length) {
    out.fields.push(leafField(def, path));
    return;
  }

  // On a container there is no text to compete with, so each attribute is a
  // field of its own (<Copy source>, <Get assignTo>, …).
  for (const attr of def.attrs || []) {
    out.fields.push({
      id: idFor([...path, attr.name]),
      label: `${labelFor(def.name)} — ${labelFor(attr.name)}`,
      type: attr.values && attr.values.length > 1 ? 'attr-select' : 'attr',
      path,
      attr: attr.name,
      ...(attr.values && attr.values.length > 1 ? { options: ['', ...attr.values] } : {}),
      ...(attr.doc ? { help: attr.doc } : {}),
    } as PolicyField);
  }

  const list = listChild(def);
  if (list) {
    const named = (list.attrs || []).some((a) => a.name === 'name');
    out.fields.push(
      named
        ? { id: idFor(path), label: labelFor(def.name), type: 'kv-list', path, itemTag: list.name, ...(def.doc ? { help: def.doc } : {}) }
        : { id: idFor(path), label: labelFor(def.name), type: 'string-list', path, itemTag: list.name, ...(def.doc ? { help: def.doc } : {}) }
    );
    return;
  }

  for (const child of children) {
    if (EDITOR_OWNED.has(child.name)) continue;
    if (child.repeatable && (child.children || []).length) {
      out.skipped.push(child.name);
      continue;
    }
    if (path.length + 1 > MAX_PATH_DEPTH) {
      out.skipped.push(child.name);
      continue;
    }
    fieldsFor(child, [...path, child.name], out);
  }
}

function rootAttrsFor(root: XmlElementDef): RootAttrDef[] {
  return (root.attrs || []).map((a) => ({
    name: a.name,
    label: labelFor(a.name),
    kind: a.values && a.values.length > 1 ? ('select' as const) : ('text' as const),
    ...(a.values && a.values.length > 1 ? { options: ['', ...a.values] } : {}),
  }));
}

/**
 * Builds a visual schema for `rootTag` out of the generated catalogue.
 *
 * Sections follow the policy's own shape: each container directly under the
 * root becomes a section, and the root's own leaf elements collect into one.
 * That is not a design so much as a refusal to invent one — the reference
 * groups a policy's elements the way its authors think about them, and
 * second-guessing that per policy is the hand-written schemas' job.
 */
export function deriveSchema(rootTag: string): PolicySchema | undefined {
  const root = GENERATED_POLICY_ELEMENTS[rootTag];
  if (!root) return undefined;

  const sections: PolicyFieldSection[] = [];
  const loose: Derived = { fields: [], skipped: [] };

  // <Parameters><Parameter/></Parameters> routinely has the scraper record
  // <Parameter> at the root as well, from a fragment that showed it alone.
  // The list owns it; a second field for the same element at the wrong depth
  // would write a sibling Apigee ignores.
  const ownedByList = new Set<string>();
  for (const child of root.children || []) {
    const list = listChild(child);
    if (list) ownedByList.add(list.name);
  }

  for (const child of root.children || []) {
    if (EDITOR_OWNED.has(child.name)) continue;
    if (ownedByList.has(child.name) && !(child.children || []).length) continue;

    if (child.repeatable && (child.children || []).length) {
      loose.skipped.push(child.name);
      continue;
    }
    if (!(child.children || []).length) {
      fieldsFor(child, [child.name], loose);
      continue;
    }

    const derived: Derived = { fields: [], skipped: [] };
    fieldsFor(child, [child.name], derived);
    if (!derived.fields.length && !derived.skipped.length) continue;
    sections.push({
      title: labelFor(child.name),
      fields: derived.fields,
      ...(derived.skipped.length ? { note: repeatNote(derived.skipped) } : {}),
    });
  }

  if (loose.fields.length) {
    sections.unshift({ title: 'Settings', fields: loose.fields });
  }
  if (loose.skipped.length) {
    sections.push({ title: 'Repeating elements', fields: [], note: repeatNote(loose.skipped) });
  }
  if (!sections.length) return undefined;

  const rootAttrs = rootAttrsFor(root);
  return { rootTag, ...(rootAttrs.length ? { rootAttrs } : {}), sections, derived: true };
}

function repeatNote(names: string[]): string {
  const unique = [...new Set(names)];
  const list = unique.map((n) => `<${n}>`).join(', ');
  return `${list} ${unique.length === 1 ? 'repeats' : 'repeat'} with nested content, which the visual editor can't represent — edit ${unique.length === 1 ? 'it' : 'them'} in the XML tab. Anything you change here leaves ${unique.length === 1 ? 'it' : 'them'} untouched.`;
}
