import {
  Activity,
  AlertCircle,
  AlertTriangle,
  Archive,
  ArrowDownToLine,
  ArrowLeft,
  ArrowRight,
  ArrowRightCircle,
  ArrowUpFromLine,
  Asterisk,
  BadgeCheck,
  BarChart2,
  Braces,
  BrainCircuit,
  Bug,
  BugOff,
  Check,
  CheckCircle,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleDollarSign,
  CircleHelp,
  CircleSlash,
  ClipboardCopy,
  ClipboardList,
  Code,
  Coffee,
  Copy,
  Crosshair,
  Database,
  Download,
  Edit3,
  Eraser,
  ExternalLink,
  FileCheck,
  FileCheck2,
  FileCode,
  FileCode2,
  FileDiff,
  FileInput,
  FileJson,
  FileJson2,
  FilePen,
  FilePlus,
  FileScan,
  FileSearch,
  FileSignature,
  FileText,
  Fingerprint,
  FlaskConical,
  FolderCode,
  Gavel,
  GitBranch,
  GitCompare,
  GitFork,
  Globe,
  Globe2,
  History,
  IdCard,
  ImageDown,
  Info,
  Key,
  KeyRound,
  Layers,
  Layers3,
  LayoutDashboard,
  LayoutTemplate,
  Lightbulb,
  ListChecks,
  ListOrdered,
  ListTree,
  Lock,
  MinusCircle,
  Moon,
  Network,
  OctagonAlert,
  Package,
  PackageOpen,
  PackagePlus,
  PanelLeft,
  Pencil,
  PhoneOutgoing,
  Play,
  PlayCircle,
  Plus,
  PlusCircle,
  Puzzle,
  Radar,
  Radio,
  RadioTower,
  Receipt,
  Redo2,
  RefreshCw,
  Replace,
  RotateCcw,
  Route,
  Save,
  ScanLine,
  ScrollText,
  Search,
  Send,
  SendHorizontal,
  Server,
  ServerOff,
  Settings2,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShieldHalf,
  Shuffle,
  Signpost,
  SlidersHorizontal,
  Sparkles,
  Split,
  Terminal,
  Trash,
  Trash2,
  TriangleAlert,
  Type,
  Undo2,
  Unlink,
  Upload,
  UserCog,
  UserSearch,
  Wand2,
  Waypoints,
  Workflow,
  X,
  XCircle,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

/**
 * Every icon the app can render, keyed by the kebab-case name `<Icon name>`
 * takes. The list is explicit on purpose: the old `import * as Icons` plus a
 * runtime lookup defeated tree-shaking and pulled the entire lucide set
 * (~760 kB, well over half the bundle) into the build.
 *
 * Names arrive from two places — literals in JSX, and the `icon` field on
 * policy/chain metadata the server seeds (see server/src/lib/policyTemplates.js
 * and server/src/seed/policyChains.js). Adding an icon in either place means
 * adding it here too, or it renders the `Puzzle` fallback.
 */
export const ICONS: Record<string, LucideIcon> = {
  'activity': Activity,
  'alert-circle': AlertCircle,
  'alert-triangle': AlertTriangle,
  'archive': Archive,
  'arrow-down-to-line': ArrowDownToLine,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-right-circle': ArrowRightCircle,
  'arrow-up-from-line': ArrowUpFromLine,
  'asterisk': Asterisk,
  'badge-check': BadgeCheck,
  'bar-chart-2': BarChart2,
  'braces': Braces,
  'brain-circuit': BrainCircuit,
  'bug': Bug,
  'bug-off': BugOff,
  'check': Check,
  'check-circle': CheckCircle,
  'check-circle-2': CheckCircle2,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'circle-dollar-sign': CircleDollarSign,
  'circle-help': CircleHelp,
  'circle-slash': CircleSlash,
  'clipboard-copy': ClipboardCopy,
  'clipboard-list': ClipboardList,
  'code': Code,
  'coffee': Coffee,
  'copy': Copy,
  'crosshair': Crosshair,
  'database': Database,
  'download': Download,
  'edit-3': Edit3,
  'eraser': Eraser,
  'external-link': ExternalLink,
  'file-check': FileCheck,
  'file-check-2': FileCheck2,
  'file-code': FileCode,
  'file-code-2': FileCode2,
  'file-diff': FileDiff,
  'file-input': FileInput,
  'file-json': FileJson,
  'file-json-2': FileJson2,
  'file-pen': FilePen,
  'file-plus': FilePlus,
  'file-scan': FileScan,
  'file-search': FileSearch,
  'file-signature': FileSignature,
  'file-text': FileText,
  'fingerprint': Fingerprint,
  'flask-conical': FlaskConical,
  'folder-code': FolderCode,
  'gavel': Gavel,
  'git-branch': GitBranch,
  'git-compare': GitCompare,
  'git-fork': GitFork,
  'globe': Globe,
  'globe-2': Globe2,
  'history': History,
  'id-card': IdCard,
  'image-down': ImageDown,
  'info': Info,
  'key': Key,
  'key-round': KeyRound,
  'layers': Layers,
  'layers-3': Layers3,
  'layout-dashboard': LayoutDashboard,
  'layout-template': LayoutTemplate,
  'lightbulb': Lightbulb,
  'list-checks': ListChecks,
  'list-ordered': ListOrdered,
  'list-tree': ListTree,
  'lock': Lock,
  'minus-circle': MinusCircle,
  'moon': Moon,
  'network': Network,
  'octagon-alert': OctagonAlert,
  'package': Package,
  'package-open': PackageOpen,
  'package-plus': PackagePlus,
  'panel-left': PanelLeft,
  'pencil': Pencil,
  'phone-outgoing': PhoneOutgoing,
  'play': Play,
  'play-circle': PlayCircle,
  'plus': Plus,
  'plus-circle': PlusCircle,
  'puzzle': Puzzle,
  'radar': Radar,
  'radio': Radio,
  'radio-tower': RadioTower,
  'receipt': Receipt,
  'redo-2': Redo2,
  'refresh-cw': RefreshCw,
  'replace': Replace,
  'rotate-ccw': RotateCcw,
  'route': Route,
  'save': Save,
  'scan-line': ScanLine,
  'scroll-text': ScrollText,
  'search': Search,
  'send': Send,
  'send-horizontal': SendHorizontal,
  'server': Server,
  'server-off': ServerOff,
  'settings-2': Settings2,
  'shield': Shield,
  'shield-alert': ShieldAlert,
  'shield-check': ShieldCheck,
  'shield-half': ShieldHalf,
  'shuffle': Shuffle,
  'signpost': Signpost,
  'sliders-horizontal': SlidersHorizontal,
  'sparkles': Sparkles,
  'split': Split,
  'terminal': Terminal,
  'trash': Trash,
  'trash-2': Trash2,
  'triangle-alert': TriangleAlert,
  'type': Type,
  'undo-2': Undo2,
  'unlink': Unlink,
  'upload': Upload,
  'user-cog': UserCog,
  'user-search': UserSearch,
  'wand-2': Wand2,
  'waypoints': Waypoints,
  'workflow': Workflow,
  'x': X,
  'x-circle': XCircle,
};

/** Shown when a name has no entry above — same fallback as before. */
export const FALLBACK_ICON: LucideIcon = Puzzle;
