import { useEffect, useMemo, useState } from 'react';
import { useStore } from '../store/useStore';
import { Icon } from './Icon';
import { EntityJumpButton } from './EntityJumpButton';
import { findEntityJump } from '../lib/entityLinks';
import type { Prerequisite, PrerequisiteKind, Proxy } from '../types/proxy';

const KIND_META: Record<PrerequisiteKind, { label: string; icon: string }> = {
  targetServer: { label: 'Target Servers', icon: 'server' },
  keystore: { label: 'Keystores', icon: 'key-round' },
  truststore: { label: 'Truststores', icon: 'shield-check' },
  kvm: { label: 'Key Value Maps', icon: 'layers' },
  cache: { label: 'Caches', icon: 'database' },
  serviceAccount: { label: 'Service Accounts', icon: 'user-cog' },
  sharedFlow: { label: 'Shared Flows', icon: 'git-branch' },
  apiProduct: { label: 'API Products', icon: 'package' },
};

const KIND_ORDER: PrerequisiteKind[] = [
  'targetServer',
  'sharedFlow',
  'kvm',
  'cache',
  'keystore',
  'truststore',
  'serviceAccount',
  'apiProduct',
];

function checklistKey(proxyId: string, item: Prerequisite): string {
  return `apigee-proxy-studio:prereq:${proxyId}:${item.kind}:${item.name}`;
}

function useChecked(proxyId: string, item: Prerequisite): [boolean, () => void] {
  const key = checklistKey(proxyId, item);
  const [checked, setChecked] = useState(() => localStorage.getItem(key) === '1');
  const toggle = () => {
    const next = !checked;
    setChecked(next);
    if (next) localStorage.setItem(key, '1');
    else localStorage.removeItem(key);
  };
  return [checked, toggle];
}

function PrereqRow({ proxy, item }: { proxy: Proxy; item: Prerequisite }) {
  const [checked, toggle] = useChecked(proxy.id, item);
  const [copied, setCopied] = useState(false);
  const jump = findEntityJump(item.source, proxy);
  const copy = () => {
    if (!item.cli) return;
    navigator.clipboard.writeText(item.cli).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    });
  };
  return (
    <div className="entity-row" style={{ alignItems: 'flex-start', opacity: checked ? 0.55 : 1 }}>
      <input type="checkbox" checked={checked} onChange={toggle} style={{ marginTop: 3, flexShrink: 0 }} title="I've created this" />
      <div style={{ flex: 1, minWidth: 0 }}>
        <div style={{ fontSize: 13, fontWeight: 600, display: 'flex', gap: 8, alignItems: 'baseline', flexWrap: 'wrap' }}>
          <span className="mono">{item.name}</span>
          <span className="field-hint">{item.source}</span>
        </div>
        {item.detail && <div className="field-hint" style={{ marginTop: 3 }}>{item.detail}</div>}
        {item.cli && (
          <pre
            className="mono"
            style={{
              marginTop: 6,
              fontSize: 11,
              background: 'var(--bg-2)',
              padding: '8px 10px',
              borderRadius: 'var(--radius-sm, 6px)',
              overflowX: 'auto',
              whiteSpace: 'pre',
            }}
          >
            {item.cli}
          </pre>
        )}
      </div>
      {jump && <EntityJumpButton jump={jump} />}
      {item.cli && (
        <button className="btn btn-sm btn-ghost" style={{ flexShrink: 0 }} onClick={copy}>
          <Icon name={copied ? 'check' : 'copy'} size={12} /> {copied ? 'Copied' : 'Copy'}
        </button>
      )}
    </div>
  );
}

function buildShellScript(items: Prerequisite[]): string {
  const lines = ['#!/usr/bin/env bash', 'set -euo pipefail', '', '# Generated by Apigee Proxy Studio — fill in $ORG / $ENV / $TOKEN (and HOST for target servers) first.', ''];
  for (const kind of KIND_ORDER) {
    const group = items.filter((i) => i.kind === kind);
    if (!group.length) continue;
    lines.push(`# --- ${KIND_META[kind].label} ---`);
    for (const item of group) {
      if (item.cli) {
        lines.push(item.cli);
      } else {
        lines.push(`# ${item.name} (${item.source}) — create manually: ${item.detail || 'no CLI template for this kind'}`);
      }
    }
    lines.push('');
  }
  return lines.join('\n');
}

export function PrerequisitesPanel() {
  const proxy = useStore((s) => s.currentProxy)!;
  const prerequisites = useStore((s) => s.prerequisites);
  const prerequisitesLoading = useStore((s) => s.prerequisitesLoading);
  const loadPrerequisites = useStore((s) => s.loadPrerequisites);
  const selectedEnvironmentId = useStore((s) => s.selectedEnvironmentId);
  const [scriptCopied, setScriptCopied] = useState(false);

  useEffect(() => {
    loadPrerequisites();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [JSON.stringify(proxy.targets), JSON.stringify(proxy.policies), selectedEnvironmentId]);

  const grouped = useMemo(() => {
    const items = prerequisites || [];
    return KIND_ORDER.map((kind) => ({ kind, items: items.filter((i) => i.kind === kind) })).filter((g) => g.items.length > 0);
  }, [prerequisites]);

  const copyScript = () => {
    if (!prerequisites?.length) return;
    navigator.clipboard.writeText(buildShellScript(prerequisites)).then(() => {
      setScriptCopied(true);
      setTimeout(() => setScriptCopied(false), 1500);
    });
  };

  return (
    <div className="card">
      <div className="row-between">
        <div>
          <h4 className="card-title">
            <Icon name="clipboard-list" size={15} /> Deployment Prerequisites
          </h4>
          <p className="card-subtitle">
            External org/environment artifacts this proxy depends on but the bundle itself doesn't contain. The console
            won't tell you any of this — check each off as you create it.
          </p>
        </div>
        {!!prerequisites?.length && (
          <button className="btn btn-sm" onClick={copyScript}>
            <Icon name={scriptCopied ? 'check' : 'terminal'} size={13} /> {scriptCopied ? 'Copied' : 'Copy all as shell script'}
          </button>
        )}
      </div>

      {prerequisitesLoading && !prerequisites && (
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '16px 0' }}>
          <span className="spinner" /> Checking…
        </div>
      )}

      {prerequisites && prerequisites.length === 0 && (
        <p className="field-hint" style={{ marginTop: 10 }}>
          Nothing found — this proxy has no Target Servers, KVMs, caches, shared flow calls, or other external
          dependencies to provision.
        </p>
      )}

      {grouped.length > 0 && (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 16, marginTop: 12 }}>
          {grouped.map(({ kind, items }) => (
            <div key={kind}>
              <div className="section-label" style={{ marginTop: 0, display: 'flex', alignItems: 'center', gap: 6 }}>
                <Icon name={KIND_META[kind].icon} size={13} /> {KIND_META[kind].label}
                <span className="field-hint">({items.length})</span>
              </div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
                {items.map((item, i) => (
                  <PrereqRow key={`${item.kind}-${item.name}-${i}`} proxy={proxy} item={item} />
                ))}
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
